"""added updated_at column on Notes

Revision ID: 13e51c09bb30
Revises: a8e2b6a26eba
Create Date: 2026-06-15 08:39:08.704431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e51c09bb30'
down_revision: Union[str, Sequence[str], None] = 'a8e2b6a26eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'updated_at')
    # ### end Alembic commands ###
