"""added relationship and minor size adjustments

Revision ID: f8db0e62014b
Revises: 94e8a1108bd7
Create Date: 2026-06-08 17:46:54.552401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f8db0e62014b"
down_revision: Union[str, Sequence[str], None] = "94e8a1108bd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "note", "title", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_index(op.f("ix_note_owner"), "note", ["owner"], unique=False)

    # The new column replaces the old plain password.
    # The new column is non nullable, so if the existing records in the table will have null for this new column, which will cause an error.
    # NOTE: Make the new column "password_hash" nullable, then fill the data, then make it non nullable
    op.add_column(
        "user", sa.Column("password_hash", sa.String(length=200), nullable=False)
    )
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("user", "password_hash")
    op.drop_index(op.f("ix_note_owner"), table_name="note")
    op.alter_column(
        "note", "title", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
